using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using TwoClassesOneNs_NS_A;
using TwoClassesOneNs_NS_B;
namespace TwoClassesOneNs_NS_B
{
    [TestFixture]
    public class Class2_autogenerated
    {
        [Test]
        public void Method1_autogenerated()
        {
            Assert.Fail("autogenerated");
        }
    }
}