using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using OneClass_NS;
namespace OneClass_NS
{
    [TestFixture]
    public class OneClass_autogenerated
    {
        [Test]
        public void Method1_autogenerated()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2_autogenerated()
        {
            Assert.Fail("autogenerated");
        }
    }
}