using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using TwoClassesOneNs_NS;
namespace TwoClassesOneNs_NS
{
    [TestFixture]
    public class Class1_autogenerated
    {
        [Test]
        public void Method1_autogenerated()
        {
            Assert.Fail("autogenerated");
        }
    }
}